### ISSUE TITLE
workdir is duplicated in tls client key and cert paths unless absolute paths used

### ISSUE THREAD

**Issue by macfarla** [ConsenSys/orion#418]
tlsclientkey and tlsclientcert relative paths do not resolve relative to the workdir but rather workdir/workdir

```
workdir = "workdir/orion1"
tls = "strict"
tlsclientkey = "my-tls-client-key.pem"
tlsclientcert = "my-tls-client-cert.pem"

```
Gives this error:

```
[INFO ] [main] 03-24-2021 11:22:09 n.c.o.c.Orion - using working directory workdir/orion1
[ERROR] [main] 03-24-2021 11:22:10 n.c.o.c.Orion - Unexpected exception upon starting Orion
io.vertx.core.VertxException: io.vertx.core.file.FileSystemException: java.nio.file.NoSuchFileException: /Users/sallymacfarlane/workspace/besu-local-nodes/workdir/orion1/workdir/orion1/my-tls-client-key.pem
	at io.vertx.core.net.impl.SSLHelper.createContext(SSLHelper.java:318) ~[vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.net.impl.SSLHelper.getContext(SSLHelper.java:493) ~[vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.net.impl.SSLHelper.validate(SSLHelper.java:518) ~[vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.http.impl.HttpClientImpl.<init>(HttpClientImpl.java:133) ~[vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.impl.VertxImpl.createHttpClient(VertxImpl.java:309) ~[vertx-core-3.7.1.jar:3.7.1]
	at net.consensys.orion.network.NodeHttpClientBuilder.build(NodeHttpClientBuilder.java:87) ~[orion-develop.jar:develop]
	at net.consensys.orion.payload.DistributePayloadManager.<init>(DistributePayloadManager.java:79) ~[orion-develop.jar:develop]
	at net.consensys.orion.cmd.Orion.run(Orion.java:431) ~[orion-develop.jar:develop]
	at net.consensys.orion.cmd.Orion.run(Orion.java:352) ~[orion-develop.jar:develop]
	at net.consensys.orion.cmd.Orion.main(Orion.java:136) [orion-develop.jar:develop]
```
Also using the default values gives similar error ie commenting out tlsclientkey and tlsclientcert values
```
[INFO ] [main] 03-24-2021 11:39:40 n.c.o.c.Orion - using working directory workdir/orion1
[ERROR] [main] 03-24-2021 11:39:40 n.c.o.c.Orion - Unexpected exception upon starting Orion
io.vertx.core.VertxException: io.vertx.core.file.FileSystemException: java.nio.file.NoSuchFileException: /Users/sallymacfarlane/workspace/besu-local-nodes/workdir/orion1/workdir/orion1/tls-client-key.pem
```

if I specify the absolute path it works:
```
tlsclientcert = "/Users/sallymacfarlane/workspace/besu-local-nodes/workdir/orion1/my-tls-client-cert.pem"
tlsclientkey = "/Users/sallymacfarlane/workspace/besu-local-nodes/workdir/orion1/my-tls-client-key.pem"
```

### Versions (Add all that apply)
* Software version: [`orion --version`]
Reproduced with orion 20.1.0 and latest master  b5c4ff2
* Java version: [`java -version`]
openjdk version "11.0.2" 2019-01-15

### Additional Information
Full config file:
```
workdir = "workdir/orion1"

nodeurl = "http://127.0.0.1:8081/"
nodeport = 8081
nodenetworkinterface = "0.0.0.0"

clienturl = "http://127.0.0.1:8881/"
clientport = 8881
clientnetworkinterface = "0.0.0.0"

tls = "strict"
#tlsclientkey = "my-tls-client-key.pem"
#tlsclientcert = "my-tls-client-cert.pem"

othernodes = ["http://127.0.0.1:8081","http://127.0.0.1:8082","http://127.0.0.1:8083"]

publickeys = ["keys/orion.pub"]
privatekeys = ["keys/orion.key"]
```

**Comment by vmichalik** [comment]
@macfarla is this issue still relevant, or should it be closed?

**Comment by macfarla** [comment]
the easy workaround is to use absolute path so we can stick with that
