### ISSUE TITLE
Test sending multiple tx to Orion w PostGres

### ISSUE THREAD

**Issue by macfarla** [ConsenSys/orion#422]
Run concurrentPrivateTransactions example against Orion using a Postgres or Oracle db
Does it generate primary key or index violations

https://towardsdatascience.com/local-development-set-up-of-postgresql-with-docker-c022632f13ea

**Comment by macfarla** [comment]
This is to test out a theory since I am getting PK violations when running against an empty tessera db but not a "migrated" tessera db

**Comment by macfarla** [comment]
```2021-04-13 15:56:47.766+10:00 | vert.x-worker-thread-13 | ERROR | DefaultPrivacyController | Failed to store private transaction in enclave
org.hyperledger.besu.enclave.EnclaveClientException: Unique index or primary key violation: "PUBLIC.PRIMARY_KEY_6 ON PUBLIC.PRIVACY_GROUP(ID) VALUES 2"; SQL statement:
INSERT INTO PRIVACY_GROUP (ID, DATA, LOOKUP_ID, TIMESTAMP) VALUES (?, ?, ?, ?) [23505-200]
	at org.hyperledger.besu.enclave.Enclave.parseResponse(Enclave.java:173)
	at org.hyperledger.besu.enclave.Enclave.handleJsonResponse(Enclave.java:162)
	at org.hyperledger.besu.enclave.Enclave.lambda$send$0(Enclave.java:66)
	at org.hyperledger.besu.enclave.VertxRequestTransmitter.lambda$handleResponse$2(VertxRequestTransmitter.java:100)
	at io.vertx.core.http.impl.HttpClientResponseImpl$BodyHandler.notifyHandler(HttpClientResponseImpl.java:292)
	at io.vertx.core.http.impl.HttpClientResponseImpl.lambda$bodyHandler$0(HttpClientResponseImpl.java:193)
	at io.vertx.core.http.impl.HttpClientResponseImpl.handleEnd(HttpClientResponseImpl.java:248)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.lambda$beginResponse$0(Http1xClientConnection.java:483)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:237)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:127)```

**Comment by MadelineMurray** [comment]
Waiting on a fix overnight (Wednesday) before this will work.

**Comment by macfarla** [comment]
I have run the concurrentPrivateTx example against Orion using PostGres (using docker image as per above link) and it works fine. 

`storage="sql:jdbc:postgresql://localhost:5432/postgres?user=postgres&password=Pass2020!"`
